[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "your_randomly_generated_string_here"

[auth.okta]
client_id = "xxx"
client_secret = "xxx"
server_metadata_url = "https://{organisation}.okta.com/.well-known/openid-configuration"

[auth.google]
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
